DROP TABLE IF EXISTS public.feat_cancion CASCADE;
DROP TABLE IF EXISTS public.lista_cancion CASCADE;
DROP TABLE IF EXISTS public.lista_reproduccion CASCADE;
DROP TABLE IF EXISTS public.cancion CASCADE;
DROP TABLE IF EXISTS public.artista CASCADE;
DROP TABLE IF EXISTS public.usuario CASCADE;


--
-- PostgreSQL database dump
--

\restrict gdnRUbQCTFcPjLi7vhpJxczHCHDAStUd3fSFxghlYW6RgMiNWHFZSIs1oUklEZ2

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-09 16:31:17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16404)
-- Name: artista; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.artista (
    id integer NOT NULL,
    nombre character varying(255) NOT NULL,
    oyentes integer DEFAULT 0 NOT NULL,
    verificado boolean DEFAULT false NOT NULL,
    seguidores integer DEFAULT 0 NOT NULL,
    cancion_mas_escuchada character varying(255)
);


ALTER TABLE public.artista OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16503)
-- Name: artista_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.artista ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.artista_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16411)
-- Name: cancion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cancion (
    id_artista integer CONSTRAINT cancion_idartista_not_null NOT NULL,
    nombre character varying(255) NOT NULL,
    reproducciones integer DEFAULT 0 NOT NULL,
    duracion interval NOT NULL,
    portada character varying(500)
);


ALTER TABLE public.cancion OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16531)
-- Name: feat_cancion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feat_cancion (
    nombre_cancion character varying(255) NOT NULL,
    id_artista integer NOT NULL,
    id_artista_feat integer NOT NULL
);


ALTER TABLE public.feat_cancion OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16566)
-- Name: lista_cancion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lista_cancion (
    id_lista integer NOT NULL,
    id_usuario integer NOT NULL,
    nombre_cancion character varying(255) NOT NULL,
    id_artista integer NOT NULL
);


ALTER TABLE public.lista_cancion OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16471)
-- Name: lista_reproduccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lista_reproduccion (
    id integer NOT NULL,
    id_usuario integer NOT NULL,
    seguidores integer DEFAULT 0 NOT NULL,
    aleatorio boolean DEFAULT false,
    publica boolean DEFAULT false,
    descripcion character varying,
    nombre character varying(255) NOT NULL,
    fecha_creacion date DEFAULT CURRENT_DATE
);


ALTER TABLE public.lista_reproduccion OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16524)
-- Name: lista_reproduccion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lista_reproduccion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lista_reproduccion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16430)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    nombre character varying(255) NOT NULL,
    seguidores integer DEFAULT 0 NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16504)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4888 (class 2606 OID 16410)
-- Name: artista artista_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.artista
    ADD CONSTRAINT artista_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 16417)
-- Name: cancion cancion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cancion
    ADD CONSTRAINT cancion_pkey PRIMARY KEY (nombre, id_artista);


--
-- TOC entry 4896 (class 2606 OID 16538)
-- Name: feat_cancion feat_cancion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feat_cancion
    ADD CONSTRAINT feat_cancion_pkey PRIMARY KEY (nombre_cancion, id_artista, id_artista_feat);


--
-- TOC entry 4898 (class 2606 OID 16574)
-- Name: lista_cancion lista_cancion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lista_cancion
    ADD CONSTRAINT lista_cancion_pkey PRIMARY KEY (id_lista, id_usuario, nombre_cancion, id_artista);


--
-- TOC entry 4894 (class 2606 OID 16478)
-- Name: lista_reproduccion lista_reproduccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lista_reproduccion
    ADD CONSTRAINT lista_reproduccion_pkey PRIMARY KEY (id, id_usuario);


--
-- TOC entry 4892 (class 2606 OID 16458)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 16418)
-- Name: cancion cancion_idartista_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cancion
    ADD CONSTRAINT cancion_idartista_fkey FOREIGN KEY (id_artista) REFERENCES public.artista(id);


--
-- TOC entry 4902 (class 2606 OID 16544)
-- Name: feat_cancion feat_cancion_id_artista_feat_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feat_cancion
    ADD CONSTRAINT feat_cancion_id_artista_feat_fkey FOREIGN KEY (id_artista_feat) REFERENCES public.artista(id);


--
-- TOC entry 4903 (class 2606 OID 16539)
-- Name: feat_cancion feat_cancion_nombre_cancion_id_artista_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feat_cancion
    ADD CONSTRAINT feat_cancion_nombre_cancion_id_artista_fkey FOREIGN KEY (nombre_cancion, id_artista) REFERENCES public.cancion(nombre, id_artista);


--
-- TOC entry 4899 (class 2606 OID 16549)
-- Name: artista fk_cancion_mas_escuchada; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.artista
    ADD CONSTRAINT fk_cancion_mas_escuchada FOREIGN KEY (id, cancion_mas_escuchada) REFERENCES public.cancion(id_artista, nombre);


--
-- TOC entry 4901 (class 2606 OID 16479)
-- Name: lista_reproduccion fk_usuario_lista; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lista_reproduccion
    ADD CONSTRAINT fk_usuario_lista FOREIGN KEY (id_usuario) REFERENCES public.usuario(id);


--
-- TOC entry 4904 (class 2606 OID 16575)
-- Name: lista_cancion lista_cancion_id_lista_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lista_cancion
    ADD CONSTRAINT lista_cancion_id_lista_id_usuario_fkey FOREIGN KEY (id_lista, id_usuario) REFERENCES public.lista_reproduccion(id, id_usuario);


--
-- TOC entry 4905 (class 2606 OID 16580)
-- Name: lista_cancion lista_cancion_nombre_cancion_id_artista_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lista_cancion
    ADD CONSTRAINT lista_cancion_nombre_cancion_id_artista_fkey FOREIGN KEY (nombre_cancion, id_artista) REFERENCES public.cancion(nombre, id_artista);


-- Completed on 2026-06-09 16:31:17

--
-- PostgreSQL database dump complete
--

\unrestrict gdnRUbQCTFcPjLi7vhpJxczHCHDAStUd3fSFxghlYW6RgMiNWHFZSIs1oUklEZ2

