spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:8080/spotify
spring.datasource.username=postgres
spring.datasource.password=Pincharata18
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
spring.jpa.properties.hibernate.default_schema=public
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method